#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
eval `dircolors ~/.dircolors`

alias rm='nocorrect rm'
ulimit -c unlimited
unsetopt SHARE_HISTORY
setopt CLOBBER
setopt DVORAK

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

function kubectl() {
  if ! type __start_kubectl >/dev/null 2>&1; then
    source <(command kubectl completion zsh)
  fi

  command kubectl "$@"
}

function helm() {
  if ! type __start_helm >/dev/null 2>&1; then
    source <(command helm completion zsh)
  fi

  command helm "$@"
}
